export const CALENDAR_TITLE_MAX_LENGTH = 20;
export const CALENDAR_DESCRIPTION_MAX_LENGTH = 200;

export const CALENDAR_TITLE_LIMIT_MESSAGE = `제목은 ${CALENDAR_TITLE_MAX_LENGTH}자까지 입력할 수 있어요.`;
export const CALENDAR_DESCRIPTION_LIMIT_MESSAGE = `설명은 최대 ${CALENDAR_DESCRIPTION_MAX_LENGTH}자까지 입력할 수 있어요.`;
